# Question No. 1:
What are the different data structures used in Tensorflow? Give some examples.

## Answer:
- **Tensors:** Tensors are the fundamental data structure in TensorFlow, representing multi-dimensional arrays of data. They can be scalar (0-dimensional), vector (1-dimensional), matrices (2-dimensional), or higher-dimensional arrays. Tensors are used for storing and processing the input data, intermediate computations, and output predictions.

- **Variables:** Variables are mutable tensors that can be updated during training. They are often used to store the learnable parameters of a machine learning model, such as weights and biases. TensorFlow provides the tf.Variable class for creating and manipulating variables.

- **Sparse Tensors:** Sparse tensors are a specialized form of tensors used to efficiently represent and process sparse data, where most of the values are zero. They store only the non-zero elements along with their indices. TensorFlow provides the tf.sparse.SparseTensor class for working with sparse data.

- **Ragged Tensors:** Ragged tensors are used to handle sequences or arrays with varying lengths. Unlike regular tensors where all dimensions have fixed sizes, ragged tensors allow for dynamic lengths along one or more dimensions. TensorFlow provides the tf.RaggedTensor class for working with ragged data.

- **Datasets:** TensorFlow Datasets (TFDS) is a library that provides pre-processed datasets for machine learning tasks. It provides an abstraction for handling large-scale data efficiently by representing it as a sequence of elements. The tf.data.Dataset class is used to create, transform, and manipulate datasets in TensorFlow.

- **Queues:** Queues are used for asynchronous data loading and processing, especially when dealing with large datasets that do not fit entirely in memory. TensorFlow provides various queue implementations, such as tf.queue.FIFOQueue and tf.queue.PaddingFIFOQueue, to facilitate efficient data pipeline management.

# Question No. 2:
How does the TensorFlow constant differ from a TensorFlow variable? Explain with an examples.

## Answer:
In TensorFlow, both constants and variables are used to store and manipulate data, but they have some key differences in terms of their properties and usage.

**TensorFlow Constant:**
- A constant in TensorFlow represents a fixed value that remains unchanged throughout the execution of a computation graph.
- Once a constant is defined, its value cannot be modified.
- Constants are typically used for storing fixed input data or hyperparameters that do not require updating during training.
- The values of constants are known and explicitly provided during the graph construction.
- Example:

In [7]:
import tensorflow as tf

x = tf.constant(5.0)
y = x * 2

print(y)

tf.Tensor(10.0, shape=(), dtype=float32)


**TensorFlow Variable:**
- A variable in TensorFlow represents a mutable tensor that can hold values that are updated during the execution of a computation graph.
- Variables are typically used for storing learnable parameters, such as weights and biases, in machine learning models.
- The values of variables are not known initially and are usually initialized randomly or with specific initialization techniques.
- Variables can be modified and updated through operations like assignment (tf.Variable.assign) or using optimizers during training.
- Example:

In [8]:
import tensorflow as tf

x = tf.Variable(5.0)
print(x)

#modifying variable
x.assign(7.0)
print(x)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=7.0>


# Question No. 3:
Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.

## Answer:
In TensorFlow, matrix addition, multiplication, and element-wise operations can be performed using various functions and operators. Let's explore each operation in detail:

**Matrix Addition:**
- Matrix addition involves adding two matrices of the same shape element-wise.
- In TensorFlow, matrix addition can be performed using the tf.add() function or the + operator.
- Example:

In [9]:
import tensorflow as tf

#define two matrices
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

#matrix addition using tf.add()
C = tf.add(A, B)

#matrix addition using the + operator
D = A + B

print(C)
print(D)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


**Matrix Multiplication:**
- Matrix multiplication involves multiplying two matrices to obtain a new matrix based on specific rules.
- In TensorFlow, matrix multiplication can be performed using the tf.matmul() function or the @ operator.
- The dimensions of the matrices must be compatible for multiplication (e.g., the number of columns in the first matrix should be equal to the number of rows in the second matrix).
- Example:

In [10]:
import tensorflow as tf

#define two matrices
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

#matrix multiplication using tf.matmul()
C = tf.matmul(A, B)

#matrix multiplication using the @ operator
D = A @ B

print(C)
print(D)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


**Element-wise Operations:**
- Element-wise operations involve applying an operation to corresponding elements of two matrices, resulting in a new matrix with the same shape.
- In TensorFlow, element-wise operations can be performed using functions or operators, such as tf.add(), tf.subtract(), tf.multiply(), tf.divide(), etc.
- Example

In [11]:
import tensorflow as tf

#define two matrices
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

#element-wise addition using tf.add()
C = tf.add(A, B)

#element-wise subtraction using tf.subtract()
D = tf.subtract(A, B)

#element-wise multiplication using tf.multiply()
E = tf.multiply(A, B)

#element-wise division using tf.divide()
F = tf.divide(A, B)

print(C)
print(D)
print(E)
print(F)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)


# Question No. 4 to 8:
4. Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the values of matrix A
5. Create a Gaussian matrix B with dimensions x, using TensorFlow's truncated_normal function. Display the values of matrix B
6. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 2 and a standard deviation of 0.x, using TensorFlow's random.normal function. Display the values of matrix C
7. Perform matrix addition between matrix A and matrix B, and store the result in matrix D
8. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E

## Answer:

In [12]:
import tensorflow as tf

#4: Create matrix A using random_normal
A = tf.random.normal(shape=(2, 2))
print("Matrix A using random_normal: ", A)

#5: Create matrix B using truncated_normal
B = tf.random.truncated_normal(shape=(2, 2))
print("Matrix B using truncated_normal: ", B)

#6: Create matrix C using random.normal
C = tf.random.normal(shape=(2, 2), mean=2, stddev=0.2)
print("Matrix C where values are drawn from normal distribution with mean=2 and std. dev=0.2: ", C)

#7: Perform matrix addition between A and B to get D
D = tf.add(A, B)
print("Matrix D (A + B): ", D)

#8: Perform matrix multiplication between C and D to get E
E = tf.matmul(C, D)
print("Matrix E (C * D): ", E)

Matrix A using random_normal:  tf.Tensor(
[[ 0.7931007   0.26117915]
 [-0.45915928  0.61354005]], shape=(2, 2), dtype=float32)
Matrix B using truncated_normal:  tf.Tensor(
[[ 0.10371255 -1.0586861 ]
 [ 0.977343   -0.3046532 ]], shape=(2, 2), dtype=float32)
Matrix C where values are drawn from normal distribution with mean=2 and std. dev=0.2:  tf.Tensor(
[[2.0399768 2.2202601]
 [2.2156212 2.0355844]], shape=(2, 2), dtype=float32)
Matrix D (A + B):  tf.Tensor(
[[ 0.8968133  -0.797507  ]
 [ 0.5181837   0.30888686]], shape=(2, 2), dtype=float32)
Matrix E (C * D):  tf.Tensor(
[[ 2.979981  -0.9410866]
 [ 3.0418053 -1.1382082]], shape=(2, 2), dtype=float32)


# Question 8 to 12:
8. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform function
9. Calculate the transpose of matrix F and store the result in matrix G
10. Calculate the element-wise exponential of matrix F and store the result in matrix H
11. Create a matrix I by concatenating matrix F and matrix G horizontally
12. Create a matrix J by concatenating matrix F and matrix H vertically

## Answer:

In [13]:
import tensorflow as tf

#8: Create matrix F using random_uniform
F = tf.random.uniform(shape=(2, 2))
print("Matrix F using random_uniform: ", F)

#9: Calculate the transpose of F to get G
G = tf.transpose(F)
print("Matrix G (Transpose of F): ", G)

#10: Calculate the element-wise exponential of F to get H
H = tf.exp(F)
print("Matrix H (Element-wise Exponential of F): ", H)

#11: Create matrix I by concatenating F and G horizontally
I = tf.concat([F, G], axis=1)
print("Matrix I (Horizontal Concatenation of F and G): ", I)

#12: Create matrix J by concatenating F and H vertically
J = tf.concat([F, H], axis=0)
print("Matrix J (Vertical Concatenation of F and H): ", J)

Matrix F using random_uniform:  tf.Tensor(
[[0.4748937  0.19927704]
 [0.7383524  0.6679841 ]], shape=(2, 2), dtype=float32)
Matrix G (Transpose of F):  tf.Tensor(
[[0.4748937  0.7383524 ]
 [0.19927704 0.6679841 ]], shape=(2, 2), dtype=float32)
Matrix H (Element-wise Exponential of F):  tf.Tensor(
[[1.6078433 1.22052  ]
 [2.0924852 1.9503018]], shape=(2, 2), dtype=float32)
Matrix I (Horizontal Concatenation of F and G):  tf.Tensor(
[[0.4748937  0.19927704 0.4748937  0.7383524 ]
 [0.7383524  0.6679841  0.19927704 0.6679841 ]], shape=(2, 4), dtype=float32)
Matrix J (Vertical Concatenation of F and H):  tf.Tensor(
[[0.4748937  0.19927704]
 [0.7383524  0.6679841 ]
 [1.6078433  1.22052   ]
 [2.0924852  1.9503018 ]], shape=(4, 2), dtype=float32)
