In [1]:
#numpy: numerical python
import numpy as np

In [2]:
l = [1,2,3,4]

In [4]:
ar=np.array(l)

In [5]:
type(ar)

numpy.ndarray

In [7]:
np.array([[1,2],[3,4]]) #2 dimensional

array([[1, 2],
       [3, 4]])

In [8]:
np.asarray(l)

array([1, 2, 3, 4])

In [9]:
a = [2,3,4]

In [10]:
np.asanyarray(a)

array([2, 3, 4])

In [11]:
b = np.matrix(l)

In [12]:
b # matrix is two-dimensional by default

matrix([[1, 2, 3, 4]])

In [13]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

matrix is also a form of array so np.asanyarray will not convert it to the main numpy array

In [14]:
np.asarray(b)

array([[1, 2, 3, 4]])

In [15]:
a = np.array(l)

In [16]:
c = a

c = a is called 'swallow copying'. now both c and a are pointing to the same array in memory. so if you alter any one of them, the changes will happen in the other as well

In [17]:
c

array([1, 2, 3, 4])

In [18]:
a

array([1, 2, 3, 4])

In [19]:
c[0] = 100

In [20]:
c

array([100,   2,   3,   4])

In [21]:
a

array([100,   2,   3,   4])

In [22]:
d = np.copy(a)

to avoid 'swallow copying' we can use np.copy() method. which copies the array to a new location in memory. this is called 'deep copying'

In [23]:
d

array([100,   2,   3,   4])

In [24]:
a

array([100,   2,   3,   4])

In [25]:
a[1]=400

In [26]:
a

array([100, 400,   3,   4])

In [27]:
d

array([100,   2,   3,   4])

creating numpy array form function:

In [29]:
np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
np.fromfunction(lambda i,j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

creating numpy array from iterable

In [32]:
iterable = (i*i for i in range(5))

In [33]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

creating numpy array from string

In [35]:
np.fromstring('234 234', sep=' ')

array([234., 234.])

In [36]:
np.fromstring('234,234', sep=',')

array([234., 234.])

### some fuctions in numpy

np.ndim

In [37]:
l = [2,3,4,5,6]

In [38]:
ar = np.array(l)

In [40]:
ar

array([2, 3, 4, 5, 6])

In [41]:
ar.ndim

1

In [42]:
ar2 = np.array([[1,3,4,5],[3,4,5,6]])

In [44]:
ar2

array([[1, 3, 4, 5],
       [3, 4, 5, 6]])

In [45]:
ar2.ndim

2

.shape

In [46]:
ar.shape

(5,)

In [47]:
ar2.shape

(2, 4)

.dtype

In [48]:
ar2.dtype

dtype('int64')

In [49]:
ar.dtype

dtype('int64')

In [50]:
ar22 = np.array([(1.4,45,45),(23,45,66)])

In [51]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [52]:
ar22.dtype

dtype('float64')

lets say we want to genarate some numerical data. we can do so by using range function as

In [53]:
list(range(5))

[0, 1, 2, 3, 4]

but now lets say we want to generate floating data, range function cannot do that

In [54]:
list(range(0.1, 0.5))

TypeError: 'float' object cannot be interpreted as an integer

in such case, we can use np.arange

np.arange:

In [55]:
np.arange(2.3, 5.6)

array([2.3, 3.3, 4.3, 5.3])

In [56]:
np.arange(2.3, 5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [57]:
list(np.arange(2.3, 5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

np.linspace:

generates linear datapoints between two points

In [58]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

np.logspace:

In [75]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [76]:
np.logspace(2,5,10, base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

np.zeros:

In [59]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [60]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [64]:
np.ndim(np.zeros((3,4,2)))

3

In [65]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [66]:
ar4=np.zeros((3,4,2,3))
ar4.ndim

4

np.ones:

In [67]:
np.ones(4)

array([1., 1., 1., 1.])

In [68]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [69]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [70]:
arr = np.ones((2,3,2))

In [71]:
arr+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [72]:
arr*5

array([[[5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.]]])

np.empty:

In [73]:
np.empty((3,5))

array([[4.67219873e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.32404027e-322]])

np.eye: identity matrix

In [74]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

np.random.randn: 

generates data that has a normal distribution

In [77]:
np.random.randn(3,4)

array([[ 2.07786183, -0.28290117, -0.10490164, -0.52157381],
       [-1.7998945 ,  1.54462186,  1.1013888 ,  2.33911968],
       [ 0.45706052, -0.28996102,  0.64021109, -0.95367926]])

In [78]:
arr = np.random.randn(3,4)

In [79]:
import pandas as pd

pd.DataFrame(arr)

0         1         2         3
0  0.429364  0.939767  0.303846 -0.091169
1 -0.164928 -0.465841 -0.627595 -0.271633
2  0.134161 -0.407692  0.055432 -1.044990

np.random.rand:

generates completely random data

In [80]:
np.random.rand(3,4)

array([[0.0720102 , 0.8319091 , 0.5093169 , 0.31734637],
       [0.12868132, 0.94774333, 0.06457269, 0.08654814],
       [0.65635706, 0.61223592, 0.77390757, 0.22027864]])

np.random.randint:

generates random integer

In [81]:
np.random.randint(3,5)

4

In [82]:
np.random.randint(34,5666)

4883

In [87]:
np.random.randint(1,100,(3,4))

array([[35, 81, 37, 55],
       [96, 57, 45,  6],
       [90, 63, 88, 53]])

In [89]:
data=np.random.randint(1,100,(3,4))

In [90]:
pd.DataFrame(data)

0   1   2   3
0   4  64  88  89
1  13  44  68  19
2  54  26  45  81

.reshape:

In [92]:
arr = np.random.rand(3,4)

In [94]:
arr

array([[0.91059694, 0.36011621, 0.93507688, 0.63769407],
       [0.57580237, 0.7626059 , 0.51376558, 0.94714948],
       [0.70196865, 0.22300105, 0.5560007 , 0.0937329 ]])

In [93]:
arr.reshape(6,2)

array([[0.91059694, 0.36011621],
       [0.93507688, 0.63769407],
       [0.57580237, 0.7626059 ],
       [0.51376558, 0.94714948],
       [0.70196865, 0.22300105],
       [0.5560007 , 0.0937329 ]])

In [95]:
arr.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [96]:
#if we know the number of rows but want the program to chose the number of cols
arr.reshape(6,-1)

array([[0.91059694, 0.36011621],
       [0.93507688, 0.63769407],
       [0.57580237, 0.7626059 ],
       [0.51376558, 0.94714948],
       [0.70196865, 0.22300105],
       [0.5560007 , 0.0937329 ]])

### slicing/indexing:

In [97]:
arr1 = arr.reshape(6,-1)

In [98]:
arr1

array([[0.91059694, 0.36011621],
       [0.93507688, 0.63769407],
       [0.57580237, 0.7626059 ],
       [0.51376558, 0.94714948],
       [0.70196865, 0.22300105],
       [0.5560007 , 0.0937329 ]])

In [99]:
arr1[1]

array([0.93507688, 0.63769407])

In [100]:
arr1[1][1]

0.6376940736652432

In [106]:
arr1[2:5,1]

array([0.7626059 , 0.94714948, 0.22300105])

In [116]:
arr = np.random.randint(1,100,(5,5))

In [117]:
arr

array([[22, 72, 21, 52, 94],
       [42, 76, 39, 71, 29],
       [ 1,  6, 53, 52, 14],
       [32, 51, 21, 48, 83],
       [83, 74, 78, 25,  5]])

In [118]:
# Extract elements that are greater than 50
arr>50

array([[False,  True, False,  True,  True],
       [False,  True, False,  True, False],
       [False, False,  True,  True, False],
       [False,  True, False, False,  True],
       [ True,  True,  True, False, False]])

In [119]:
arr[arr>50]

array([72, 52, 94, 76, 71, 53, 52, 51, 83, 83, 74, 78])

In [122]:
arr[2:4,1:3]

array([[ 6, 53],
       [51, 21]])

In [125]:
arr[2:4,[1,2]]

array([[ 6, 53],
       [51, 21]])

In [126]:
arr[0][0]

22

In [127]:
arr[0][0]=5000

In [128]:
arr

array([[5000,   72,   21,   52,   94],
       [  42,   76,   39,   71,   29],
       [   1,    6,   53,   52,   14],
       [  32,   51,   21,   48,   83],
       [  83,   74,   78,   25,    5]])

### more functions

In [129]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [130]:
arr1

array([[1, 2, 1],
       [2, 1, 2],
       [2, 1, 1]])

In [131]:
arr2

array([[1, 2, 1],
       [2, 2, 1],
       [1, 1, 1]])

In [132]:
arr1+arr2

array([[2, 4, 2],
       [4, 3, 3],
       [3, 2, 2]])

In [133]:
arr1-arr2

array([[ 0,  0,  0],
       [ 0, -1,  1],
       [ 1,  0,  0]])

In [134]:
arr1*arr2

array([[1, 4, 1],
       [4, 2, 2],
       [2, 1, 1]])

### matrix multiplication

In [135]:
arr1

array([[1, 2, 1],
       [2, 1, 2],
       [2, 1, 1]])

In [136]:
arr2

array([[1, 2, 1],
       [2, 2, 1],
       [1, 1, 1]])

In [137]:
  arr1@arr2

array([[6, 7, 4],
       [6, 8, 5],
       [5, 7, 4]])

In [138]:
arr1/0

/tmp/ipykernel_152/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [139]:
arr1+100

array([[101, 102, 101],
       [102, 101, 102],
       [102, 101, 101]])

In [142]:
arr1**2

array([[1, 4, 1],
       [4, 1, 4],
       [4, 1, 1]])

### numpy broadcasting

In [143]:
arr = np.zeros((4,4))

In [144]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [146]:
row = np.array([1,2,3,4])

In [147]:
row

array([1, 2, 3, 4])

In [148]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [150]:
row.shape

(4,)

In [153]:
col = np.array([[1,2,3,4]])

In [154]:
col

array([[1, 2, 3, 4]])

In [155]:
col.transpose()

array([[1],
       [2],
       [3],
       [4]])

In [156]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [157]:
col.T+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [160]:
arr1 = np.random.randint(1,4,(3,4))

In [161]:
arr1

array([[3, 2, 1, 3],
       [3, 3, 2, 1],
       [1, 3, 2, 1]])

In [162]:
np.exp(arr1)

array([[20.08553692,  7.3890561 ,  2.71828183, 20.08553692],
       [20.08553692, 20.08553692,  7.3890561 ,  2.71828183],
       [ 2.71828183, 20.08553692,  7.3890561 ,  2.71828183]])

In [163]:
np.log10(arr1)

array([[0.47712125, 0.30103   , 0.        , 0.47712125],
       [0.47712125, 0.47712125, 0.30103   , 0.        ],
       [0.        , 0.47712125, 0.30103   , 0.        ]])

# More Numpy

In [167]:
arr = np.random.randint(1,10,(3,4))

In [168]:
arr

array([[4, 2, 6, 3],
       [4, 9, 9, 7],
       [5, 2, 9, 2]])

In [169]:
arr.reshape(6,2)

array([[4, 2],
       [6, 3],
       [4, 9],
       [9, 7],
       [5, 2],
       [9, 2]])

In [170]:
arr.reshape(2,6)

array([[4, 2, 6, 3, 4, 9],
       [9, 7, 5, 2, 9, 2]])

In [171]:
arr.reshape(3,-134)

array([[4, 2, 6, 3],
       [4, 9, 9, 7],
       [5, 2, 9, 2]])

In [172]:
arr.T

array([[4, 4, 5],
       [2, 9, 2],
       [6, 9, 9],
       [3, 7, 2]])

In [173]:
arr.flatten()

array([4, 2, 6, 3, 4, 9, 9, 7, 5, 2, 9, 2])

In [205]:
arr1 = np.array([1,2,3,4])

In [188]:
arr1.ndim

1

In [189]:
np.expand_dims(arr1, axis=1) #expannd dimension on columns

array([[1],
       [2],
       [3],
       [4]])

In [190]:
np.expand_dims(arr1, axis=0) #expand dimension on row

array([[1, 2, 3, 4]])

In [193]:
data = np.array([[1],[2],[3]])

In [194]:
data

array([[1],
       [2],
       [3]])

In [196]:
data.ndim

2

In [195]:
np.squeeze(data) #squeeze dimensions

array([1, 2, 3])

In [198]:
(np.squeeze(data)).ndim

1

In [199]:
arr1

array([1, 2, 3, 4])

In [200]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [201]:
np.roll(arr1,2)

array([3, 4, 1, 2])

In [202]:
np.diag(arr1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### binary operations

In [210]:
arr1 = np.random.randint(1,10,(3,4))

In [209]:
arr2 = np.random.randint(1,10,(3,4))

In [211]:
arr1

array([[3, 4, 4, 9],
       [6, 4, 3, 3],
       [5, 3, 5, 8]])

In [212]:
arr2

array([[5, 6, 9, 1],
       [9, 7, 5, 2],
       [3, 8, 4, 9]])

In [213]:
arr1+arr2

array([[ 8, 10, 13, 10],
       [15, 11,  8,  5],
       [ 8, 11,  9, 17]])

In [214]:
arr1*arr2

array([[15, 24, 36,  9],
       [54, 28, 15,  6],
       [15, 24, 20, 72]])

In [215]:
arr1/arr2

array([[0.6       , 0.66666667, 0.44444444, 9.        ],
       [0.66666667, 0.57142857, 0.6       , 1.5       ],
       [1.66666667, 0.375     , 1.25      , 0.88888889]])

In [216]:
arr1-arr2

array([[-2, -2, -5,  8],
       [-3, -3, -2,  1],
       [ 2, -5,  1, -1]])

In [217]:
arr1%arr2

array([[3, 4, 4, 0],
       [6, 4, 3, 1],
       [2, 3, 1, 8]])

In [218]:
arr1**arr2

array([[      243,      4096,    262144,         9],
       [ 10077696,     16384,       243,         9],
       [      125,      6561,       625, 134217728]])

In [219]:
arr1&arr2

array([[1, 4, 0, 1],
       [0, 4, 1, 2],
       [1, 0, 4, 8]])

In [220]:
arr1

array([[3, 4, 4, 9],
       [6, 4, 3, 3],
       [5, 3, 5, 8]])

In [221]:
~arr1

array([[ -4,  -5,  -5, -10],
       [ -7,  -5,  -4,  -4],
       [ -6,  -4,  -6,  -9]])

In [222]:
arr1|arr2

array([[ 7,  6, 13,  9],
       [15,  7,  7,  3],
       [ 7, 11,  5,  9]])

In [228]:
arr1

array([[3, 4, 4, 9],
       [6, 4, 3, 3],
       [5, 3, 5, 8]])

In [229]:
arr2

array([[5, 6, 9, 1],
       [9, 7, 5, 2],
       [3, 8, 4, 9]])

In [227]:
arr1[arr1>arr2]

array([9, 3, 5, 5])

### string functions

In [231]:
arr=np.array(['sudh','kumar'])

In [232]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [233]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [234]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [236]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

### mathematical functions

In [237]:
arr1

array([[3, 4, 4, 9],
       [6, 4, 3, 3],
       [5, 3, 5, 8]])

In [238]:
np.sin(arr1)

array([[ 0.14112001, -0.7568025 , -0.7568025 ,  0.41211849],
       [-0.2794155 , -0.7568025 ,  0.14112001,  0.14112001],
       [-0.95892427,  0.14112001, -0.95892427,  0.98935825]])

In [239]:
np.cos(arr1)

array([[-0.9899925 , -0.65364362, -0.65364362, -0.91113026],
       [ 0.96017029, -0.65364362, -0.9899925 , -0.9899925 ],
       [ 0.28366219, -0.9899925 ,  0.28366219, -0.14550003]])

In [240]:
np.tan(arr1)

array([[-0.14254654,  1.15782128,  1.15782128, -0.45231566],
       [-0.29100619,  1.15782128, -0.14254654, -0.14254654],
       [-3.38051501, -0.14254654, -3.38051501, -6.79971146]])

In [241]:
np.tanh(arr1)

array([[0.99505475, 0.9993293 , 0.9993293 , 0.99999997],
       [0.99998771, 0.9993293 , 0.99505475, 0.99505475],
       [0.9999092 , 0.99505475, 0.9999092 , 0.99999977]])

In [242]:
np.log10(arr1)

array([[0.47712125, 0.60205999, 0.60205999, 0.95424251],
       [0.77815125, 0.60205999, 0.47712125, 0.47712125],
       [0.69897   , 0.47712125, 0.69897   , 0.90308999]])

In [243]:
np.exp(arr1)

array([[  20.08553692,   54.59815003,   54.59815003, 8103.08392758],
       [ 403.42879349,   54.59815003,   20.08553692,   20.08553692],
       [ 148.4131591 ,   20.08553692,  148.4131591 , 2980.95798704]])

In [244]:
np.sqrt(arr1)

array([[1.73205081, 2.        , 2.        , 3.        ],
       [2.44948974, 2.        , 1.73205081, 1.73205081],
       [2.23606798, 1.73205081, 2.23606798, 2.82842712]])

In [246]:
np.power(arr1,2)

array([[ 9, 16, 16, 81],
       [36, 16,  9,  9],
       [25,  9, 25, 64]])

In [248]:
np.mean(arr1)

4.75

In [250]:
np.median(arr1)

4.0

In [251]:
np.std(arr1)

1.920286436967152

In [252]:
np.var(arr1)

3.6875

In [253]:
np.min(arr1)

3

In [254]:
np.max(arr1)

9

# More numpy

### Sort, Search and Counting Functions

In [256]:
arr = np.array([4,5,6,7,89,5,6,7,8,2,45,7])

In [257]:
arr

array([ 4,  5,  6,  7, 89,  5,  6,  7,  8,  2, 45,  7])

In [258]:
np.sort(arr)

array([ 2,  4,  5,  5,  6,  6,  7,  7,  7,  8, 45, 89])

In [259]:
np.searchsorted(arr,34) #where can i store 34 in the sorted array

12

In [260]:
arr1 = np.array([0,342,543,2,1,0,0,0])

In [261]:
np.count_nonzero(arr1)

4

In [262]:
arr

array([ 4,  5,  6,  7, 89,  5,  6,  7,  8,  2, 45,  7])

In [263]:
np.where(arr>6)

(array([ 3,  4,  7,  8, 10, 11]),)

In [264]:
np.extract(arr>6, arr) 

array([ 7, 89,  7,  8, 45,  7])

In [266]:
#byte swapping
arr.byteswap()

array([ 288230376151711744,  360287970189639680,  432345564227567616,
        504403158265495552, 6413125869375586304,  360287970189639680,
        432345564227567616,  504403158265495552,  576460752303423488,
        144115188075855872, 3242591731706757120,  504403158265495552])

In [269]:
arr

array([ 4,  5,  6,  7, 89,  5,  6,  7,  8,  2, 45,  7])

In [268]:
a = np.copy(arr) #deep copy

In [270]:
a

array([ 4,  5,  6,  7, 89,  5,  6,  7,  8,  2, 45,  7])

In [271]:
b = arr.view() #swallow copy

In [272]:
b

array([ 4,  5,  6,  7, 89,  5,  6,  7,  8,  2, 45,  7])

In [273]:
arr[1]=44

In [274]:
arr

array([ 4, 44,  6,  7, 89,  5,  6,  7,  8,  2, 45,  7])

In [275]:
b

array([ 4, 44,  6,  7, 89,  5,  6,  7,  8,  2, 45,  7])

In [276]:
a

array([ 4,  5,  6,  7, 89,  5,  6,  7,  8,  2, 45,  7])

### matrix library

In [277]:
import numpy.matlib as nm

In [279]:
m=nm.zeros(5)

In [280]:
m

matrix([[0., 0., 0., 0., 0.]])

In [281]:
m.ndim

2

In [282]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [283]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

### linear algebra

In [284]:
arr1 = np.random.randint([[2,3],[4,5]])

In [285]:
arr2 = np.random.randint([[5,3],[2,5]])

In [286]:
np.dot(arr1,arr2)

array([[2, 4],
       [6, 8]])

In [287]:
arr1@arr2 #matrix multiplication

array([[2, 4],
       [6, 8]])